In [448]:
# Importando o pandas
import pandas as pd

In [449]:
df_train = pd.read_csv('train.csv')

In [450]:
# Visualizando a base de treino
df_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [455]:
# Verificando as informações da base
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [456]:
# Verificando os tipos de dados
df_train.dtypes.value_counts()

int64      5
object     5
float64    2
Name: count, dtype: int64

In [457]:
# Verificando os valores vazios
df_train.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

In [458]:
# Visualizando a base de teste
df_test = pd.read_csv('test.csv')
df_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [459]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [460]:
# Verificando os valores vazios
df_test.isnull().sum().sort_values(ascending=False).head(5)

Cabin     327
Age        86
Fare        1
Name        0
Pclass      0
dtype: int64

In [461]:
# Retornando os valores vazios do treino
df_train.isnull().sum().sort_values(ascending=False).head(5)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
dtype: int64

In [462]:
# Retorna o shape da base
df_train.shape

(891, 12)

In [463]:
# Verificando a cardinalidade dos dados
df_train.nunique().sort_values(ascending=False)

PassengerId    891
Name           891
Ticket         681
Fare           248
Cabin          147
Age             88
SibSp            7
Parch            7
Embarked         3
Pclass           3
Survived         2
Sex              2
dtype: int64

In [464]:
# Eliminando da base de treino colunas com alta cardinalidade
df_train = df_train.drop(['Name', 'Ticket', 'Cabin'], axis=1)

In [465]:
# Eliminando também para a base de teste
df_test = df_test.drop(['Name', 'Ticket', 'Cabin'], axis=1)

In [466]:
# Verificando a média das idades
df_train.Age.mean()

np.float64(29.69911764705882)

In [467]:
# Podemos substituir os valores faltantes das idades plela idade média da base
df_train.loc[df_train.Age.isnull(), 'Age'] = df_train.Age.mean()

In [468]:
# Faezendo a mesma coisa para a base de teste
df_test.loc[df_test.Age.isnull(), 'Age'] = df_test.Age.mean()

In [469]:
# Verificando os valores na coluna Embarked
df_train.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [470]:
# Selecionando a moda dessa coluna
df_train.Embarked.mode()[0]

'S'

In [471]:
# Substituindo os valores vazios na coluna Embarked pela moda
df_train.loc[df_train.Embarked.isnull(), 'Embarked'] = df_train.Embarked.mode()[0]

In [472]:
# Substituindo o único valor nulo da coluna Fare da base de teste pela sua média
df_test.loc[df_test.Fare.isnull(), 'Fare'] = df_test.Fare.mean()

In [473]:
# Verificando novamente se ainda existe algum valor nulo na base de treino
df_train.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
dtype: int64

In [474]:
# Verificando novamente se ainda existe algum valor nulo na base de teste
df_test.isnull().sum().sort_values(ascending=False).head(5)

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
dtype: int64

In [475]:
# Transformando as variáveis categóricas úteis em numéricas
def transforma_sexo(valor):
    if valor == 'male':
        return 1
    else:
        return 0

def transforma_embarque(valor):
    if valor == 'S':
        return 0
    elif valor == 'C':
        return 1
    else:
        return 2

df_train.Sex = df_train.Sex.apply(transforma_sexo)
df_train.Embarked = df_train.Embarked.apply(transforma_embarque)
df_test.Sex = df_test.Sex.apply(transforma_sexo)
df_test.Embarked = df_test.Embarked.apply(transforma_embarque)

In [476]:
df_train.head()

   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         0
1            2         1       1    0  38.0      1      0  71.2833         1
2            3         1       3    0  26.0      0      0   7.9250         0
3            4         1       1    0  35.0      1      0  53.1000         0
4            5         0       3    1  35.0      0      0   8.0500         0

In [477]:
df_test.head()

   PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          892       3    1  34.5      0      0   7.8292         2
1          893       3    0  47.0      1      0   7.0000         0
2          894       2    1  62.0      0      0   9.6875         2
3          895       3    1  27.0      0      0   8.6625         0
4          896       3    0  22.0      1      1  12.2875         0

In [478]:
# Após manipular os dados, podemos escolher os modelos para classificar esses dados: Árvore de classificação, classificação dos vizinhos mais próimos, regressão logística, etc

In [479]:
# Importando o train_test_split
from sklearn.model_selection import train_test_split

In [480]:
# Separando o X e o y
X = df_train.drop(['PassengerId', 'Survived'], axis=1)
y = df_train.Survived

In [481]:
# Separando os dados de treino e teste
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.33, random_state=42)

In [482]:
# Utilizando primeiramente a árvore de classificação
from sklearn import tree

In [483]:
# Criando o classificador
clf_ac = tree.DecisionTreeClassifier(random_state=42)

In [484]:
# Fazendo o fit com os dados
clf_ac = clf_ac.fit(X_train, y_train)

In [485]:
# Fazendo a previsão com os dados
y_pred_ac = clf_ac.predict(X_val)

In [486]:
# Utilizando o KNN
from sklearn.neighbors import KNeighborsClassifier

In [487]:
# Criando o classificador
clf_knn = KNeighborsClassifier(n_neighbors=3)

In [488]:
# Fazendo o fit com os dados
clf_knn = clf_knn.fit(X_train, y_train)

In [489]:
# Fazendo a previsâo
y_pred_knn = clf_knn.predict(X_val)

In [490]:
# Utilizando a regressão logística
from sklearn.linear_model import LogisticRegression

In [491]:
# Criando o classificador
clf_lr = LogisticRegression(random_state=42)

In [492]:
# Fazendo o fit com os dados
clf_lr = clf_lr.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [493]:
# Fazendo a previsão
y_pred_lr = clf_lr.predict(X_val)

In [494]:
# Para finalizar, vamos analisar os três modelos utilizados através da acurácia

In [495]:
from sklearn.metrics import accuracy_score

In [496]:
# Para a árvore
accuracy_score(y_val, y_pred_ac)

0.7593220338983051

In [497]:
# Para o KNN
accuracy_score(y_val, y_pred_knn)

0.7152542372881356

In [498]:
# Para a regressão
accuracy_score(y_val, y_pred_lr)

0.8135593220338984

In [499]:
# Avaliando agora a matriz de confusão

In [500]:
from sklearn.metrics import confusion_matrix

In [501]:
# Para a árvore
confusion_matrix(y_val, y_pred_ac)

array([[141,  34],
       [ 37,  83]])

In [502]:
# Para o KNN
confusion_matrix(y_val, y_pred_knn)

array([[147,  28],
       [ 56,  64]])

In [503]:
# Para a regressão
confusion_matrix(y_val, y_pred_lr)

array([[153,  22],
       [ 33,  87]])

Agora, faremos a normalização dos dados para ver se alguma acurácia se dá diferente

In [504]:
# Importando o MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Selecionar só as colunas numéricas
colunas_numericas = df_train.drop(['PassengerId', 'Survived'], axis=1).select_dtypes(include=['int64', 'float64']).columns

# Aplicar normalização
df_train[colunas_numericas] = scaler.fit_transform(df_train[colunas_numericas])

df_train.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,1.0,1.0,0.271174,0.125,0.0,0.014151,0.0
1,2,1,0.0,0.0,0.472229,0.125,0.0,0.139136,0.5
2,3,1,1.0,0.0,0.321438,0.000,0.0,0.015469,0.0
3,4,1,0.0,0.0,0.434531,0.125,0.0,0.103644,0.0
4,5,0,1.0,1.0,0.434531,0.000,0.0,0.015713,0.0

In [505]:
# Fazendo o mesmo trabalho feito anteriormente, mas agora com os dados normalizados
X = df_train.drop(['PassengerId', 'Survived'], axis=1)
y = df_train.Survived
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.33, random_state=42)

In [506]:
clf_ac_norm = tree.DecisionTreeClassifier(random_state=42)
clf_ac_norm = clf_ac_norm.fit(X_train, y_train)
y_pred_ac_norm = clf_ac_norm.predict(X_val)

In [507]:
clf_knn_norm = KNeighborsClassifier(n_neighbors=3)
clf_knn_norm = clf_knn_norm.fit(X_train, y_train)
y_pred_knn_norm = clf_knn_norm.predict(X_val)

In [508]:
clf_lr_norm = LogisticRegression(random_state=42)
clf_lr_norm = clf_lr_norm.fit(X_train, y_train)
y_pred_lr_norm = clf_lr_norm.predict(X_val)

In [509]:
accuracy_score(y_val, y_pred_ac_norm)

0.7593220338983051

In [510]:
accuracy_score(y_val, y_pred_knn_norm)

0.7830508474576271

In [511]:
accuracy_score(y_val, y_pred_lr_norm)

0.8135593220338984

Após normalizar os dados, vimos que o único modelo que sofreu um efeito positivo da normalização foi o KNN, que passou de uma acurácia de 71,5% para 78,3%. Porém, a regressão logística, tanto com normalização quanto sem, mostrou a melhor acurácia, com 81%. Então, ela será a escolhida para tratar os dados de teste

In [512]:
# Visualizando o X_train
X_train.head()

     Pclass  Sex       Age  SibSp     Parch      Fare  Embarked
6       0.0  1.0  0.673285  0.000  0.000000  0.101229       0.0
718     1.0  1.0  0.367921  0.000  0.000000  0.030254       1.0
685     0.5  1.0  0.308872  0.125  0.333333  0.081157       0.5
73      1.0  1.0  0.321438  0.125  0.000000  0.028213       0.5
882     1.0  0.0  0.271174  0.000  0.000000  0.020527       0.0

In [513]:
# Fazendo a normalização para os dados de teste
scaler = MinMaxScaler()

# Selecionar só as colunas numéricas
colunas_numericas = df_test.drop(['PassengerId'], axis=1).select_dtypes(include=['int64', 'float64']).columns

# Aplicar normalização
df_test[colunas_numericas] = scaler.fit_transform(df_test[colunas_numericas])

df_test.head()

   PassengerId  Pclass  Sex       Age  SibSp     Parch      Fare  Embarked
0          892     1.0  1.0  0.452723  0.000  0.000000  0.015282       1.0
1          893     1.0  0.0  0.617566  0.125  0.000000  0.013663       0.0
2          894     0.5  1.0  0.815377  0.000  0.000000  0.018909       1.0
3          895     1.0  1.0  0.353818  0.000  0.000000  0.016908       0.0
4          896     1.0  0.0  0.287881  0.125  0.111111  0.023984       0.0

In [514]:
# Visualizando a base de teste (apenas com os valores numéricos)
df_test.head()

   PassengerId  Pclass  Sex       Age  SibSp     Parch      Fare  Embarked
0          892     1.0  1.0  0.452723  0.000  0.000000  0.015282       1.0
1          893     1.0  0.0  0.617566  0.125  0.000000  0.013663       0.0
2          894     0.5  1.0  0.815377  0.000  0.000000  0.018909       1.0
3          895     1.0  1.0  0.353818  0.000  0.000000  0.016908       0.0
4          896     1.0  0.0  0.287881  0.125  0.111111  0.023984       0.0

In [515]:
# Para a base de teste ser igual a base de treino, precisamos eliminar a coluna de Id
X_teste = df_test.drop('PassengerId', axis=1)

In [516]:
# Utilizando a regressão logística na base de teste
y_pred = clf_lr_norm.predict(X_teste)

In [517]:
# Criando uma nova coluna de previsão na base de teste
df_test['Survived'] = y_pred
df_test.head()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Survived
0,892,1.0,1.0,0.452723,0.000,0.000000,0.015282,1.0,0
1,893,1.0,0.0,0.617566,0.125,0.000000,0.013663,0.0,0
2,894,0.5,1.0,0.815377,0.000,0.000000,0.018909,1.0,0
3,895,1.0,1.0,0.353818,0.000,0.000000,0.016908,0.0,0
4,896,1.0,0.0,0.287881,0.125,0.111111,0.023984,0.0,1

In [518]:
# Selecionando apenas a coluna Id e Survived para fazer o envio
base_envio = df_test[['PassengerId', 'Survived']]
base_envio.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [519]:
# Exportando para um csv
base_envio.to_csv('resultado2.csv', index=False)